INSERT INTO WallType (name) VALUES ('Кирпич');
INSERT INTO WallType (name) VALUES ('Панель');
INSERT INTO WallType (name) VALUES ('Железо-бетон');
INSERT INTO WallType (name) VALUES ('Железо-бетонные плиты');
INSERT INTO WallType (name) VALUES ('Железо-бетонные панели');
INSERT INTO WallType (name) VALUES ('монолит');
INSERT INTO WallType (name) VALUES ('Газоблок');
INSERT INTO WallType (name) VALUES ('Бетон');
INSERT INTO WallType (name) VALUES ('Пеноблок');
INSERT INTO WallType (name) VALUES ('камень-ракушечник');
INSERT INTO WallType (name) VALUES ('шлакоблок');
INSERT INTO WallType (name) VALUES ('Сплитерные блоки');
INSERT INTO WallType (name) VALUES ('ж/б блоки');
INSERT INTO WallType (name) VALUES ('газобетонные блоки');
INSERT INTO WallType (name) VALUES ('ж/б каркас запол. шлакоблоки');
INSERT INTO WallType (name) VALUES ('монолитный теплоблок');
INSERT INTO WallType (name) VALUES ('ж/б монолит');
INSERT INTO WallType (name) VALUES ('камень');
INSERT INTO WallType (name) VALUES ('запол. пенобетон. бл. ж/б кар. с');
INSERT INTO WallType (name) VALUES ('Крупноблочный');
INSERT INTO WallType (name) VALUES ('Шлакобетон');
INSERT INTO WallType (name) VALUES ('теплоблок');
INSERT INTO WallType (name) VALUES ('керамзитоблоки');
INSERT INTO WallType (name) VALUES ('шлаколитой');
INSERT INTO WallType (name) VALUES ('к/б блоки');
INSERT INTO WallType (name) VALUES ('Шпальный');
INSERT INTO WallType (name) VALUES ('ж/б кар. запол. кирпичом');
INSERT INTO WallType (name) VALUES ('Силикатный кирпич');
INSERT INTO WallType (name) VALUES ('Ж/б каркас заполн. пеноблоком');
INSERT INTO WallType (name) VALUES ('Беттонные блоки');
INSERT INTO WallType (name) VALUES ('ж/б панели обл кирпичом');
INSERT INTO WallType (name) VALUES ('Пескоблок');
INSERT INTO WallType (name) VALUES ('Керамзитовые блоки');
INSERT INTO WallType (name) VALUES ('Финблок');
INSERT INTO WallType (name) VALUES ('крупнопанельные');
INSERT INTO WallType (name) VALUES ('монолит, газоблок');
INSERT INTO WallType (name) VALUES ('кирп.- пан.');
INSERT INTO WallType (name) VALUES ('ж/б/кирпич/гипсокартон');
INSERT INTO WallType (name) VALUES ('монолит, пеноблок обл., кирпич');
INSERT INTO WallType (name) VALUES ('ракушеблоки обл.сил.кирп');
INSERT INTO WallType (name) VALUES ('смежный');
INSERT INTO WallType (name) VALUES ('блоки');
INSERT INTO WallType (name) VALUES ('монолит, пескоблок');
INSERT INTO WallType (name) VALUES ('монол.шлакобетон');
INSERT INTO WallType (name) VALUES ('к-засыпной');
INSERT INTO WallType (name) VALUES ('монолитный ж/б');
INSERT INTO WallType (name) VALUES ('смешанный ( ж/б плиты, кирпич, обложенные кирпичом)');
INSERT INTO WallType (name) VALUES ('Пенобетонные блоки');
INSERT INTO WallType (name) VALUES ('газобл.+пенопл.обл.силкирпичем');
INSERT INTO WallType (name) VALUES ('ж/б плиты/кирпич');
INSERT INTO WallType (name) VALUES ('кирпичный с несущей стеной');
INSERT INTO WallType (name) VALUES ('сил.кирп.облож.красн.кирп.');
INSERT INTO WallType (name) VALUES ('Тупноблочный');
INSERT INTO WallType (name) VALUES ('ж/б колонны с заполн. кирпич.');
INSERT INTO WallType (name) VALUES ('керамзитобетон');
INSERT INTO WallType (name) VALUES ('каменноленточный');
INSERT INTO WallType (name) VALUES ('каркасно-щитовой');
INSERT INTO WallType (name) VALUES ('блоки СКЦ');
INSERT INTO WallType (name) VALUES ('бетон свай');
INSERT INTO WallType (name) VALUES ('керамзитобетонные панели');
INSERT INTO WallType (name) VALUES ('ж/б кар. заполн. сплит. блок.');
INSERT INTO WallType (name) VALUES ('ж/б, пенобетон');
INSERT INTO WallType (name) VALUES ('теплоблок');
INSERT INTO WallType (name) VALUES ('железобетон/монолит');
INSERT INTO WallType (name) VALUES ('Эко-блоки обложенные кирпичом');
INSERT INTO WallType (name) VALUES ('Брусья');
INSERT INTO WallType (name) VALUES ('пескоблок. кирпич');
INSERT INTO WallType (name) VALUES ('ж/кирпич');
INSERT INTO WallType (name) VALUES ('б/кирпич');
INSERT INTO WallType (name) VALUES ('ж/б кар.зап. теплоблок');
INSERT INTO WallType (name) VALUES ('кар.кам.кирпич');
INSERT INTO WallType (name) VALUES ('кар№кам');
INSERT INTO WallType (name) VALUES ('к/кам. бревно');
INSERT INTO WallType (name) VALUES ('пескоблок');
INSERT INTO WallType (name) VALUES ('камыш');
INSERT INTO WallType (name) VALUES ('саман');
INSERT INTO WallType (name) VALUES ('кирпичный с каркасом');
INSERT INTO WallType (name) VALUES ('ж/б каркас с запол. кирпич');
INSERT INTO WallType (name) VALUES ('пескоблок');
INSERT INTO WallType (name) VALUES ('шл.блок обл. кирпичом');
INSERT INTO WallType (name) VALUES ('сб.щит.,кирпич');
INSERT INTO WallType (name) VALUES ('монолит, теплоблок');
INSERT INTO WallType (name) VALUES ('пенополистерол');
INSERT INTO WallType (name) VALUES ('пескоблоки, обложенные  кирпичом');
INSERT INTO WallType (name) VALUES ('ж/б каркас заполн. теплоблоки');
INSERT INTO WallType (name) VALUES ('газобетон.обл.кирпичем');
INSERT INTO WallType (name) VALUES ('пенобетон');
INSERT INTO WallType (name) VALUES ('ракушеблок');
INSERT INTO WallType (name) VALUES ('жженный кирпич');
INSERT INTO WallType (name) VALUES ('Монолитный бетон');
INSERT INTO WallType (name) VALUES ('ж/б плиты');
INSERT INTO WallType (name) VALUES ('ж/б плиты');
INSERT INTO WallType (name) VALUES ('Железобетонный Литой');
INSERT INTO WallType (name) VALUES ('кирпич');
INSERT INTO WallType (name) VALUES ('пенобл. обл. сил.кирп.');
INSERT INTO WallType (name) VALUES ('сил.блоки обл.ж/кирпичом');
INSERT INTO WallType (name) VALUES ('ракушечник');
INSERT INTO WallType (name) VALUES ('каркас');
INSERT INTO WallType (name) VALUES ('газобетонные');
INSERT INTO WallType (name) VALUES ('деревянный');
INSERT INTO WallType (name) VALUES ('бетонные блоки');
INSERT INTO WallType (name) VALUES ('шлак');
INSERT INTO WallType (name) VALUES ('газоблочныем обл. кирп.');
INSERT INTO WallType (name) VALUES ('силикатный кирпич');
INSERT INTO WallType (name) VALUES ('Брусчатый');
INSERT INTO WallType (name) VALUES ('ж/б панели');
INSERT INTO WallType (name) VALUES ('крупностеновые блоки');
INSERT INTO WallType (name) VALUES ('ж/бетон');
INSERT INTO WallType (name) VALUES ('крупностеновые блоки');
INSERT INTO WallType (name) VALUES ('гипсоблочные');
INSERT INTO WallType (name) VALUES ('крупноблочные');
INSERT INTO WallType (name) VALUES ('к/б');
INSERT INTO WallType (name) VALUES ('пескоблок обл. о.жж.к.');
INSERT INTO WallType (name) VALUES ('силикатный кирпич, обложенный красным кирпичом');
INSERT INTO WallType (name) VALUES ('керамз. пан. обл. кирп.');
INSERT INTO WallType (name) VALUES ('кирпичные особокапитальные');
INSERT INTO WallType (name) VALUES ('железобетонные стеновые блоки');
INSERT INTO WallType (name) VALUES ('Крупнопанельный');
INSERT INTO WallType (name) VALUES ('бревенчатый');
INSERT INTO WallType (name) VALUES ('ж/б стен. панели');
INSERT INTO WallType (name) VALUES ('саман облицованный кирпичом');
INSERT INTO WallType (name) VALUES ('сб.щит., обл. сил. к.');
INSERT INTO WallType (name) VALUES ('бут.кам');
INSERT INTO WallType (name) VALUES ('облиц. кирпичом');
INSERT INTO WallType (name) VALUES ('щит. обл. кирп. ракушечник');
INSERT INTO WallType (name) VALUES ('саман/жж. кирпич');
INSERT INTO WallType (name) VALUES ('ОСБ');
INSERT INTO WallType (name) VALUES ('кирпич/шлакоблок');
INSERT INTO WallType (name) VALUES ('панельный 158');
INSERT INTO WallType (name) VALUES ('ж/б');
INSERT INTO WallType (name) VALUES ('Р/блок');
INSERT INTO WallType (name) VALUES ('ж/б блоки облож. кирпичом');
INSERT INTO WallType (name) VALUES ('пено.блок/кипич');
INSERT INTO WallType (name) VALUES ('крупные панели');
INSERT INTO WallType (name) VALUES ('ячеистый бетон.блок');
INSERT INTO WallType (name) VALUES ('блоки ячеистого бетона');
INSERT INTO WallType (name) VALUES ('экотон');
INSERT INTO WallType (name) VALUES ('шпальные обл. сил. кир.');
INSERT INTO WallType (name) VALUES ('ж/б бл./ракушечник');
INSERT INTO WallType (name) VALUES ('сырцовый кирпич');
INSERT INTO WallType (name) VALUES ('бетон');
INSERT INTO WallType (name) VALUES ('шпалы б/у, обл. кирпичом');
INSERT INTO WallType (name) VALUES ('монолит.бетон');
INSERT INTO WallType (name) VALUES ('саман обл. силик. кирпичом');
INSERT INTO WallType (name) VALUES ('крупные шлакобетонные блоки');
INSERT INTO WallType (name) VALUES ('50% с/кирп.');
INSERT INTO WallType (name) VALUES ('к/панельные');
INSERT INTO WallType (name) VALUES ('монолит');
INSERT INTO WallType (name) VALUES ('шл/бетон');
INSERT INTO WallType (name) VALUES ('газоблоки');
INSERT INTO WallType (name) VALUES ('керамзитоблочные обл. кирп.');
INSERT INTO WallType (name) VALUES ('шлаколитой обл. плиткой');
INSERT INTO WallType (name) VALUES ('шпал. обл. кирпичом');
INSERT INTO WallType (name) VALUES ('крупные легкобетонные блоки');
INSERT INTO WallType (name) VALUES ('ст. панели');
INSERT INTO WallType (name) VALUES ('к/б бетон');
INSERT INTO WallType (name) VALUES ('горбыль');
INSERT INTO WallType (name) VALUES ('керамзито-блочный');
INSERT INTO WallType (name) VALUES ('Шлакоблоки облицованные кирпичем');
INSERT INTO WallType (name) VALUES ('крупные стеновые/ж/бетонные блоки');
INSERT INTO WallType (name) VALUES ('Железобетон');
INSERT INTO WallType (name) VALUES ('железобетон');
INSERT INTO WallType (name) VALUES ('блочный');
INSERT INTO WallType (name) VALUES ('ж/б панели');
INSERT INTO WallType (name) VALUES ('панельный');
INSERT INTO WallType (name) VALUES ('кер.бетон.панели');
INSERT INTO WallType (name) VALUES ('керамзитобетонные блоки');
INSERT INTO WallType (name) VALUES ('к/бетон обл. кирпичом');
INSERT INTO WallType (name) VALUES ('шлакобетон обл. сил. кирпич.');
INSERT INTO WallType (name) VALUES ('крупноблочные ж/б');
INSERT INTO WallType (name) VALUES ('ж/б плита');
INSERT INTO WallType (name) VALUES ('сб.щитовой');
INSERT INTO WallType (name) VALUES ('крупноблочный ж/б');
INSERT INTO WallType (name) VALUES ('керамзитные');
INSERT INTO WallType (name) VALUES ('ж/б, кирпич');
INSERT INTO WallType (name) VALUES ('шлаколитые о/к');
INSERT INTO WallType (name) VALUES ('деревянный о/к');
INSERT INTO WallType (name) VALUES ('крупно бетонные');
INSERT INTO WallType (name) VALUES ('керам.блок.обложен кирпичом');
INSERT INTO WallType (name) VALUES ('шлакаблоки');
INSERT INTO WallType (name) VALUES ('панели');
INSERT INTO WallType (name) VALUES ('горб. рубл.');
INSERT INTO WallType (name) VALUES ('панель 158');
INSERT INTO WallType (name) VALUES ('шлакозаливные');
INSERT INTO WallType (name) VALUES ('сб/щ.об.к.');
INSERT INTO WallType (name) VALUES ('кирпич с нечущей стеной');
INSERT INTO WallType (name) VALUES ('Цем.песчан болки');
INSERT INTO WallType (name) VALUES ('блоки');
INSERT INTO WallType (name) VALUES ('шлаколитой-кирпич');
INSERT INTO WallType (name) VALUES ('ж/б блоки, пеноблок');
INSERT INTO WallType (name) VALUES ('Газоблок обл. кирпичом');
INSERT INTO WallType (name) VALUES ('газоблочные');
INSERT INTO WallType (name) VALUES ('ж/б панель');
INSERT INTO WallType (name) VALUES ('пеноблок, р/б, пескоблок');
INSERT INTO WallType (name) VALUES ('?лутас');
INSERT INTO WallType (name) VALUES ('ж.ж.к');
INSERT INTO WallType (name) VALUES ('лент. бетон');
INSERT INTO WallType (name) VALUES ('камень-ракушечник');
INSERT INTO WallType (name) VALUES ('шлаклбл.-кирпичн.');
INSERT INTO WallType (name) VALUES ('монолитные обл.сил.к.');
INSERT INTO WallType (name) VALUES ('ж/б, монолит, газоблок');
INSERT INTO WallType (name) VALUES ('ж/б монолит, пеноблок, обл. кирпичом');
INSERT INTO WallType (name) VALUES ('ж/б монолит.кирпич');
INSERT INTO WallType (name) VALUES ('пескоблок, кирпич');
INSERT INTO WallType (name) VALUES ('ж/б, монолит, газоблок');
INSERT INTO WallType (name) VALUES ('теплоблок-металлоконструкции');
INSERT INTO WallType (name) VALUES ('пескоблоки');
INSERT INTO WallType (name) VALUES ('газоблоки, обл. кирпичом');
INSERT INTO WallType (name) VALUES ('ж/б монолит, кирпич');
INSERT INTO WallType (name) VALUES ('экоблок');
INSERT INTO WallType (name) VALUES ('железобетон');
INSERT INTO WallType (name) VALUES ('ж/б панели');
INSERT INTO WallType (name) VALUES ('кирпич с несущей стеной');
INSERT INTO WallType (name) VALUES ('глинобитные');
INSERT INTO WallType (name) VALUES ('мет.каркас заполн.пеноблоки');
INSERT INTO WallType (name) VALUES ('Ракушеблок');

INSERT INTO AdvertType (name) VALUES ('Продажа');
INSERT INTO AdvertType (name) VALUES ('Аренда');

INSERT INTO Source (name, url) VALUES ('krisha.kz', 'https://krisha.kz');
INSERT INTO Source (name, url) VALUES ('kn.kz', 'https://www.kn.kz');
INSERT INTO Source (name, url) VALUES ('krn.kz', 'http://krn.kz');
INSERT INTO Source (name, url) VALUES ('olx.kz', 'https://www.olx.kz');
INSERT INTO Source (name, url) VALUES ('biss.kz', 'http://biss.kz');
INSERT INTO Source (name, url) VALUES ('knopka.kz', 'http://knopka.kz');
INSERT INTO Source (name, url) VALUES ('1000ukg.kz', 'http://1000ukg.kz');
INSERT INTO Source (name, url) VALUES ('sreda.kz', 'http://sreda.kz');
INSERT INTO Source (name, url) VALUES ('azh.kz', 'http://azh.kz/ru');
INSERT INTO Source (name, url) VALUES ('lada.kz', 'https://www.lada.kz');
INSERT INTO Source (name, url) VALUES ('newregion.kz', 'http://newregion.kz');
INSERT INTO Source (name, url) VALUES ('uralsk.admir.kz', 'http://uralsk.admir.kz');
INSERT INTO Source (name, url) VALUES ('uralsk.cenotavr.kz', 'http://uralsk.cenotavr.kz');
INSERT INTO Source (name, url) VALUES ('chance.ng.kz', 'http://chance.ng.kz');
INSERT INTO Source (name, url) VALUES ('ivest.kz', 'http://ivest.kz');
INSERT INTO Source (name, url) VALUES ('shymkent.avizinfo.kz', 'http://shymkent.avizinfo.kz');
INSERT INTO Source (name, url) VALUES ('everyhouse.kz', 'http://www.everyhouse.kz');
INSERT INTO Source (name, url) VALUES ('vecherny-taldyk.ucoz.kz', 'http://vecherny-taldyk.ucoz.kz');
INSERT INTO Source (name, url) VALUES ('oeaa.b2b.ivest.kz', 'http://oeaa.b2b.ivest.kz');
INSERT INTO Source (name, url) VALUES ('irr.kz', 'http://irr.kz');